# Generated by Django 5.0.7 on 2024-08-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0005_alter_task_options_alter_tasklist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='main',
        ),
    ]
