# Generated by Django 5.0.7 on 2024-08-27 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0008_remove_subtask_tasklist_alter_subtasklist_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtasklist',
            name='task',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='TaskList.task'),
        ),
    ]
